/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 01/20/2012
 */

package org.fastcode.util;

import org.eclipse.jdt.core.IType;
import org.fastcode.common.CreateVariableData;

public interface FieldBuilder {

	/**
	 * @param type
	 * @param createVariableData
	 * @param fieldName
	 * @return
	 */
	String buildFieldSource(final IType type, final CreateVariableData createVariableData, final String fieldName);
}
