/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 12/26/2011
 */

package org.fastcode.preferences;

import static org.fastcode.preferences.PreferenceConstants.P_DATABASE_ALL_TEMPLATES;
import static org.fastcode.preferences.PreferenceConstants.P_DATABASE_TEMPLATE_PREFIX;

import org.eclipse.ui.IWorkbenchPreferencePage;

public class DatabaseTemplatePreferencePage extends AbstractTableTemplatePreferencePage implements IWorkbenchPreferencePage {

	/**
	 *
	 * This is Constructor for DatabaseTemplatePreferencePage
	 */
	public DatabaseTemplatePreferencePage() {
		super();
		this.templatePrefix = P_DATABASE_TEMPLATE_PREFIX;
		setDescription("Database Template Preference");

	}

	@Override
	protected String getAllTemplatesPreferenceKey() {
		return P_DATABASE_ALL_TEMPLATES;
	}

	/**
	 *
	 */
	@Override
	protected boolean isDetailedTemplate() {
		return false;
	}

	/**
	 *
	 */
	@Override
	protected boolean isShowAllowedFileExtension() {
		return true;
	}
}
