/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 04/02/2012
 */

package org.fastcode.common;

public class FastCodeReturn extends AbstractFastCodeType {

	/**
	 * @param name
	 * @param type
	 */
	public FastCodeReturn(final String name, final FastCodeType type) {
		super(name, type);
	}

}
