/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Biswarup
 * Created : 06/25/2014 09:43:38
 */

package org.fastcode.common;

import org.eclipse.swt.graphics.Color;

public class FastCodeColor {

	private static Color	warningMsgColor;
	private static Color	errorMsgColor;
	private static Color	warningMsgPrefPageColor;
	private static Color	blueMsgColor;
	private static Color	lineHighlightColor;

	/**
	 *
	 */
	public static Color getWarningMsgColor() {
		return warningMsgColor = warningMsgColor == null ? new Color(null, 255, 165, 0) : warningMsgColor;
	}

	/**
	 *
	 */
	public static Color getErrorMsgColor() {
		return errorMsgColor = errorMsgColor == null ? new Color(null, 255, 0, 0) : errorMsgColor;
	}

	public static Color getWarningMsgPrefPageColor() {
		return warningMsgPrefPageColor = warningMsgPrefPageColor == null ? new Color(null, 64, 96, 192) : warningMsgPrefPageColor;
	}

	public static Color getBlueMsgColor() {
		return blueMsgColor = blueMsgColor == null ? new Color(null, 255, 165, 0) : blueMsgColor;
	}

	public static Color getLineHighlightColor() {
		return lineHighlightColor = lineHighlightColor == null ? new Color(null, 236, 247, 247) : lineHighlightColor; //211, 238, 238
	}

	public static void disposeColor() {
		if (warningMsgColor != null && !warningMsgColor.isDisposed()) {
			warningMsgColor.dispose();
		}
		if (errorMsgColor != null && !errorMsgColor.isDisposed()) {
			errorMsgColor.dispose();
		}
		if (warningMsgPrefPageColor != null && !warningMsgPrefPageColor.isDisposed()) {
			warningMsgPrefPageColor.dispose();
		}

		if (blueMsgColor != null && !blueMsgColor.isDisposed()) {
			blueMsgColor.dispose();
		}

		if (lineHighlightColor != null && !lineHighlightColor.isDisposed()) {
			lineHighlightColor.dispose();
		}
	}
}
