/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : KrishV
 * Created : 09/23/2013 10:43:17
 */

package org.fastcode.common;

import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import org.fastcode.common.RepositoryFolder;



public class RepositoryFolder {

	private final String name;
	private final String author;
	private final long revision;
	private final Date revDate;
	private List<RepositoryFolder> subFolder = new ArrayList<RepositoryFolder>();
	private final String type;
	private final String path;
	private final boolean atRoot;

	/**
	 *
	 * getter method for name
	 * @return
	 *
	 */
	public String getName() {
		return this.name;
	}

	/**
	 *
	 * getter method for author
	 * @return
	 *
	 */
	public String getAuthor() {
		return this.author;
	}

	/**
	 *
	 * getter method for revision
	 * @return
	 *
	 */
	public long getRevision() {
		return this.revision;
	}

	/**
	 *
	 * getter method for revDate
	 * @return
	 *
	 */
	public Date getRevDate() {
		return this.revDate;
	}

	public List<RepositoryFolder> getSubFolder() {
		return this.subFolder;
	}

	public void setSubFolder(final List<RepositoryFolder> subFolder) {
		this.subFolder = subFolder;
	}


	/**
	 *
	 * getter method for type
	 * @return
	 *
	 */
	public String getType() {
		return this.type;
	}

	/**
	 *
	 * getter method for path
	 * @return
	 *
	 */
	public String getPath() {
		return this.path;
	}

	/**
	 *
	 * getter method for atRoot
	 * @return
	 *
	 */
	public boolean isAtRoot() {
		return this.atRoot;
	}

	private RepositoryFolder(final Builder builder){
		 this.name = builder.name;
	 this.author = builder.author;
	 this.revision = builder.revision;
	 this.revDate = builder.revDate;
	 this.subFolder = builder.subFolder;
	 this.type = builder.type;
	 this.path = builder.path;
	 this.atRoot = builder.atRoot;
}

	public static class Builder{

		private String name;
		private String author;
		private long revision;
		private Date revDate;
		private List<RepositoryFolder> subFolder = new ArrayList<RepositoryFolder>();
		private String type;
		private String path;
		private boolean atRoot;

		public Builder(){
		}

		public RepositoryFolder build() {
			return new RepositoryFolder(this);
		}

		public Builder withName(final String name) {
			this.name = name;
			return this;
		}

		public Builder withAuthor(final String author) {
			this.author = author;
			return this;
		}

		public Builder withRevision(final long revision) {
			this.revision = revision;
			return this;
		}

		public Builder withRevDate(final Date revDate) {
			this.revDate = revDate;
			return this;
		}

		public Builder withRepositoryFolder(final List<RepositoryFolder> subFolder) {
			this.subFolder = subFolder;
			return this;
		}

		public Builder withType(final String type) {
			this.type = type;
			return this;
		}

		public Builder withPath(final String path) {
			this.path = path;
			return this;
		}

		public Builder withAtRoot(final boolean atRoot) {
			this.atRoot = atRoot;
			return this;
		}
	}
}
