/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : KrishV
 * Created : 08/20/2014 05:57:16
 */

package org.fastcode.templates.util;



public class FastCodeLocalVariables {

	private String varName;
	private int scopeStartLine;
	private int scopeEndLine;
	private int varLineNo;

	public FastCodeLocalVariables(final String varName, final int scopeStartLine, final int scopeEndLine) {
		super();
		this.varName = varName;
		this.scopeStartLine = scopeStartLine;
		this.scopeEndLine = scopeEndLine;
	}

	public FastCodeLocalVariables(final String varName, final int varLineNo) {
		super();
		this.varName = varName;
		this.varLineNo = varLineNo;
	}

	/**
	 *
	 * getter method for varName
	 * @return
	 *
	 */
	public String getVarName() {
		return this.varName;
	}

	/**
	 *
	 * setter method for varName
	 * @param varName
	 *
	 */
	public void setVarName(final String varName) {
		this.varName = varName;
	}

	/**
	 *
	 * getter method for scopeStartLine
	 * @return
	 *
	 */
	public int getScopeStartLine() {
		return this.scopeStartLine;
	}

	/**
	 *
	 * setter method for scopeStartLine
	 * @param scopeStartLine
	 *
	 */
	public void setScopeStartLine(final int scopeStartLine) {
		this.scopeStartLine = scopeStartLine;
	}

	/**
	 *
	 * getter method for scopeEndLine
	 * @return
	 *
	 */
	public int getScopeEndLine() {
		return this.scopeEndLine;
	}

	/**
	 *
	 * setter method for scopeEndLine
	 * @param scopeEndLine
	 *
	 */
	public void setScopeEndLine(final int scopeEndLine) {
		this.scopeEndLine = scopeEndLine;
	}

	public int getVarLineNo() {
		return this.varLineNo;
	}


}
