/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : KrishV
 * Created : 08/20/2014 06:01:36
 */

package org.fastcode.templates.util;

import org.fastcode.templates.util.FastCodeLocalVariables;

public class SetVariable extends FastCodeLocalVariables {

	public SetVariable(final String varName, final int start, final int end) {
		super(varName, start, end);
	}
}
