/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Biswarup
 * Created : 09/08/2014 04:14:25
 */
package org.fastcode.handler;

import java.util.List;
import java.util.Map;

import org.eclipse.jdt.core.ICompilationUnit;
import org.fastcode.common.Action;
import org.fastcode.common.FastCodeConstants.TemplateTag;

public interface FCTagHandler {

	/**
	 * @param tagFound
	 * @param tagBody
	 * @param insideTagBody
	 * @param compUnit
	 * @param hasSubAction1
	 * @param placeHolders
	 * @param contextMap
	 * @param spacesBeforeCursor
	 * @param attributes
	 * @param existingMembersBuilder
	 * @param actionList
	 * @return
	 * @throws Exception
	 */
	public Action populateTagAction(TemplateTag tagFound, String tagBody, String insideTagBody, ICompilationUnit compUnit,
			boolean hasSubAction1, Map<String, Object> placeHolders, Map<String, Object> contextMap, String spacesBeforeCursor,
			Map<String, String> attributes, StringBuilder existingMembersBuilder, List<Action> actionList) throws Exception;

}