/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 09/18/2011
 */

package org.fastcode.popup.actions.snippet;

import java.util.Map;

import org.eclipse.ui.IEditorPart;

public class FieldSnippetCreator implements SnippetCreator {

	/**
	 * @param editorPart
	 * @param template
	 * @param placeHolders
	 * @param memberSelection
	 * @param spacesBeforeCursor
	 *
	 */
	@Override
	public Object createSnippet(final IEditorPart editorPart, final String template, final Map<String, Object> placeHolders,
			final Map<String, Object> memberSelection, final String spacesBeforeCursor) throws Exception {
		return null;
	}

}
