/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 09/24/2011
 */

package org.fastcode.popup.actions.snippet;

import java.io.InputStream;

public class XMLFileLoadingStrategy implements FileLoadingStrategy {

	/**
	 *
	 * @param inputStream
	 * @param configuration
	 *
	 */
	@Override
	public Object[] loadFileElementsFromInputStream(final InputStream inputStream, final Object configuration) throws Exception {
		return null;
	}

}
