/**
 * This class has been generated by Fast Code Eclipse Plugin
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Gautam
 * Created : 01/09/2012
 */

package org.fastcode.popup.actions.easycreate;

import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.ui.IActionDelegate;
import org.eclipse.ui.IWorkbenchWindowActionDelegate;
import org.fastcode.common.CreateVariableData;

public class DetailedNewClassCreateAction extends SimpleNewClassCreateAction implements IActionDelegate, IWorkbenchWindowActionDelegate {

	/**
	 *
	 */
	/* (non-Javadoc)
	 * @see org.fastcode.popup.actions.easycreate.NewMemberCreateActionSupport#getCreateVariableData(org.eclipse.jdt.core.ICompilationUnit)
	 */
	@Override
	protected CreateVariableData getCreateVariableData(final ICompilationUnit compUnit) throws Exception {
		this.createVariableData = new CreateVariableData();
		this.createVariableData.setCreateClassSimple(false);
		this.createVariableData.setCreateClassDetailed(true);
		return super.getCreateVariableData(compUnit);
	}

}
